AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ApplicationName:
    Type: String
    Description: The name of the Elastic beanstalk application
  ApplicationDescription:
    Type: String
    Description: The description of the Elastic beanstalk application
  DeploymentBucketName:
    Type: String
    Description: The name of the S3 bucket that contains the deployable bundle
  DeploymentBucketKey:
    Type: String
    Description: The S3 bucket key of deployable bundle
  ServiceRoleName:
    Type: String
    Description: The service role that the elastic beanstalk enviroment will use to manage resources
  SecurityGroupName:
    Type: String
    Description: The security group to associate with the instance

Resources:
  Application:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName:
        Ref: ApplicationName
      Description:
        Ref: ApplicationDescription

  ApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: Application
      SourceBundle:
        S3Bucket:
          Ref: DeploymentBucketName
        S3Key:
          Ref: DeploymentBucketKey
  
  InstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: 'eb-instance-role-${ApplicationName}'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName:
        Fn::Sub: 'eb-instance-profile-${ApplicationName}'
      Roles:
        - Ref: InstanceProfileRole

  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: Application
      Description: The elastic beanstalk application environment
      Tier:
        Name: WebServer
        Type: Standard
      SolutionStackName: 64bit Amazon Linux 2 v3.2.0 running Docker
      OptionSettings:
        - Namespace: aws:ec2:instances
          OptionName: InstanceTypes
          Value: t2.micro
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: SingleInstance
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value:
            Ref: ServiceRoleName
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value:
            Ref: InstanceProfile
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: SecurityGroups
          Value:
            Ref: SecurityGroupName
      VersionLabel:
        Ref: ApplicationVersion


    

